using System;
using System.ComponentModel;

namespace RpgToolsEditor.Models
{
	public sealed class ItemNameStringConverter : StringConverter
	{
		public override bool GetStandardValuesSupported(ITypeDescriptorContext context)
		{
			return true;
		}

		public override bool GetStandardValuesExclusive(ITypeDescriptorContext context)
		{
			return false;
		}

		public override TypeConverter.StandardValuesCollection GetStandardValues(ITypeDescriptorContext context)
		{
			return new StandardValuesCollection(value);
		}

		public static string[] value = new string[]
		{
			"Iron Pickaxe",
			"Dirt Block",
			"Stone Block",
			"Iron Broadsword",
			"Mushroom",
			"Iron Shortsword",
			"Iron Hammer",
			"Torch",
			"Wood",
			"Iron Axe",
			"Iron Ore",
			"Copper Ore",
			"Gold Ore",
			"Silver Ore",
			"Copper Watch",
			"Silver Watch",
			"Gold Watch",
			"Depth Meter",
			"Gold Bar",
			"Copper Bar",
			"Silver Bar",
			"Iron Bar",
			"Gel",
			"Wooden Sword",
			"Wooden Door",
			"Stone Wall",
			"Acorn",
			"Lesser Healing Potion",
			"Life Crystal",
			"Dirt Wall",
			"Bottle",
			"Wooden Table",
			"Furnace",
			"Wooden Chair",
			"Iron Anvil",
			"Work Bench",
			"Goggles",
			"Lens",
			"Wooden Bow",
			"Wooden Arrow",
			"Flaming Arrow",
			"Shuriken",
			"Suspicious Looking Eye",
			"Demon Bow",
			"War Axe Of The Night",
			"Lights Bane",
			"Unholy Arrow",
			"Chest",
			"Band Of Regeneration",
			"Magic Mirror",
			"Jesters Arrow",
			"Angel Statue",
			"Cloud In A Bottle",
			"Hermes Boots",
			"Enchanted Boomerang",
			"Demonite Ore",
			"Demonite Bar",
			"Heart",
			"Corrupt Seeds",
			"Vile Mushroom",
			"Ebonstone Block",
			"Grass Seeds",
			"Sunflower",
			"Vilethorn",
			"Starfury",
			"Purification Powder",
			"Vile Powder",
			"Rotten Chunk",
			"Worm Tooth",
			"Worm Food",
			"Copper Coin",
			"Silver Coin",
			"Gold Coin",
			"Platinum Coin",
			"Fallen Star",
			"Copper Greaves",
			"Iron Greaves",
			"Silver Greaves",
			"Gold Greaves",
			"Copper Chainmail",
			"Iron Chainmail",
			"Silver Chainmail",
			"Gold Chainmail",
			"Grappling Hook",
			"Chain",
			"Shadow Scale",
			"Piggy Bank",
			"Mining Helmet",
			"Copper Helmet",
			"Iron Helmet",
			"Silver Helmet",
			"Gold Helmet",
			"Wood Wall",
			"Wood Platform",
			"Flintlock Pistol",
			"Musket",
			"Musket Ball",
			"Minishark",
			"Iron Bow",
			"Shadow Greaves",
			"Shadow Scalemail",
			"Shadow Helmet",
			"Nightmare Pickaxe",
			"The Breaker",
			"Candle",
			"Copper Chandelier",
			"Silver Chandelier",
			"Gold Chandelier",
			"Mana Crystal",
			"Lesser Mana Potion",
			"Band Of Starpower",
			"Flower of Fire",
			"Magic Missile",
			"Dirt Rod",
			"Shadow Orb",
			"Meteorite",
			"Meteorite Bar",
			"Hook",
			"Flamarang",
			"Molten Fury",
			"Fiery Greatsword",
			"Molten Pickaxe",
			"Meteor Helmet",
			"Meteor Suit",
			"Meteor Leggings",
			"Bottled Water",
			"Space Gun",
			"Rocket Boots",
			"Gray Brick",
			"Gray Brick Wall",
			"Red Brick",
			"Red Brick Wall",
			"Clay Block",
			"Blue Brick",
			"Blue Brick Wall",
			"Chain Lantern",
			"Green Brick",
			"Green Brick Wall",
			"Pink Brick",
			"Pink Brick Wall",
			"Gold Brick",
			"Gold Brick Wall",
			"Silver Brick",
			"Silver Brick Wall",
			"Copper Brick",
			"Copper Brick Wall",
			"Spike",
			"Water Candle",
			"Book",
			"Cobweb",
			"Necro Helmet",
			"Necro Breastplate",
			"Necro Greaves",
			"Bone",
			"Muramasa",
			"Cobalt Shield",
			"Aqua Scepter",
			"Lucky Horseshoe",
			"Shiny Red Balloon",
			"Harpoon",
			"Spiky Ball",
			"Ball O' Hurt",
			"Blue Moon",
			"Handgun",
			"Water Bolt",
			"Bomb",
			"Dynamite",
			"Grenade",
			"Sand Block",
			"Glass",
			"Sign",
			"Ash Block",
			"Obsidian",
			"Hellstone",
			"Hellstone Bar",
			"Mud Block",
			"Sapphire",
			"Ruby",
			"Emerald",
			"Topaz",
			"Amethyst",
			"Diamond",
			"Glowing Mushroom",
			"Star",
			"Ivy Whip",
			"Breathing Reed",
			"Flipper",
			"Healing Potion",
			"Mana Potion",
			"Blade of Grass",
			"Thorn Chakram",
			"Obsidian Brick",
			"Obsidian Skull",
			"Mushroom Grass Seeds",
			"Jungle Grass Seeds",
			"Wooden Hammer",
			"Star Cannon",
			"Blue Phaseblade",
			"Red Phaseblade",
			"Green Phaseblade",
			"Purple Phaseblade",
			"White Phaseblade",
			"Yellow Phaseblade",
			"Meteor Hamaxe",
			"Empty Bucket",
			"Water Bucket",
			"Lava Bucket",
			"Jungle Rose",
			"Stinger",
			"Vine",
			"Feral Claws",
			"Anklet Of The Wind",
			"Staff of Regrowth",
			"Hellstone Brick",
			"Whoopie Cushion",
			"Shackle",
			"Molten Hamaxe",
			"Flamelash",
			"Phoenix Blaster",
			"Sunfury",
			"Hellforge",
			"Clay Pot",
			"Nature's Gift",
			"Bed",
			"Silk",
			"Lesser Restoration Potion",
			"Restoration Potion",
			"Jungle Hat",
			"Jungle Shirt",
			"Jungle Pants",
			"Molten Helmet",
			"Molten Breastplate",
			"Molten Greaves",
			"Meteor Shot",
			"Sticky Bomb",
			"Black Lens",
			"Sunglasses",
			"Wizard Hat",
			"Top Hat",
			"Tuxedo Shirt",
			"Tuxedo Pants",
			"Summer Hat",
			"Bunny Hood",
			"Plumbers Hat",
			"Plumbers Shirt",
			"Plumbers Pants",
			"Hero's Hat",
			"Hero's Shirt",
			"Hero's Pants",
			"Fish Bowl",
			"Archaeologist's Hat",
			"Archaeologist's Jacket",
			"Archaeologists's Pants",
			"Black Thread",
			"Green Thread",
			"Ninja Hood",
			"Ninja Shirt",
			"Ninja Pants",
			"Leather",
			"Red Hat",
			"Goldfish",
			"Robe",
			"Robot Hat",
			"Gold Crown",
			"Hellfire Arrow",
			"Sandgun",
			"Guide Voodoo Doll",
			"Diving Helmet",
			"Familiar Shirt",
			"Familiar Pants",
			"Familiar Wig",
			"Demon Scythe",
			"Nights Edge",
			"Dark Lance",
			"Coral",
			"Cactus",
			"Trident",
			"Silver Bullet",
			"Throwing Knife",
			"Spear",
			"Blowpipe",
			"Glowstick",
			"Seed",
			"Wooden Boomerang",
			"Aglet",
			"Sticky Glowstick",
			"Poisoned Knife",
			"Obsidian Skin Potion",
			"Regeneration Potion",
			"Swiftness Potion",
			"Gills Potion",
			"Ironskin Potion",
			"Mana Regeneration Potion",
			"Magic Power Potion",
			"Featherfall Potion",
			"Spelunker Potion",
			"Invisibility Potion",
			"Shine Potion",
			"Night Owl Potion",
			"Battle Potion",
			"Thorns Potion",
			"Water Walking Potion",
			"Archery Potion",
			"Hunter Potion",
			"Gravitation Potion",
			"Gold Chest",
			"Daybloom Seeds",
			"Moonglow Seeds",
			"Blinkroot Seeds",
			"Deathweed Seeds",
			"Waterleaf Seeds",
			"Fireblossom Seeds",
			"Daybloom",
			"Moonglow",
			"Blinkroot",
			"Deathweed",
			"Waterleaf",
			"Fireblossom",
			"Shark Fin",
			"Feather",
			"Tombstone",
			"Mime Mask",
			"Antlion Mandible",
			"Illegal Gun Parts",
			"The Doctor's Shirt",
			"The Doctor's Pants",
			"Golden Key",
			"Shadow Chest",
			"Shadow Key",
			"Obsidian Brick Wall",
			"Jungle Spores",
			"Loom",
			"Piano",
			"Dresser",
			"Bench",
			"Bathtub",
			"Red Banner",
			"Green Banner",
			"Blue Banner",
			"Yellow Banner",
			"Lamp Post",
			"Tiki Torch",
			"Barrel",
			"Chinese Lantern",
			"Cooking Pot",
			"Safe",
			"Skull Lantern",
			"Trash Can",
			"Candelabra",
			"Pink Vase",
			"Mug",
			"Keg",
			"Ale",
			"Bookcase",
			"Throne",
			"Bowl",
			"Bowl of Soup",
			"Toilet",
			"Grandfather Clock",
			"Armor Statue",
			"Goblin Battle Standard",
			"Tattered Cloth",
			"Sawmill",
			"Cobalt Ore",
			"Mythril Ore",
			"Adamantite Ore",
			"Pwnhammer",
			"Excalibur",
			"Hallowed Seeds",
			"Ebonsand Block",
			"Cobalt Hat",
			"Cobalt Helmet",
			"Cobalt Mask",
			"Cobalt Breastplate",
			"Cobalt Leggings",
			"Mythril Hood",
			"Mythril Helmet",
			"Mythril Hat",
			"Mythril Chainmail",
			"Mythril Greaves",
			"Cobalt Bar",
			"Mythril Bar",
			"Cobalt Chainsaw",
			"Mythril Chainsaw",
			"Cobalt Drill",
			"Mythril Drill",
			"Adamantite Chainsaw",
			"Adamantite Drill",
			"Dao of Pow",
			"Mythril Halberd",
			"Adamantite Bar",
			"Glass Wall",
			"Compass",
			"Diving Gear",
			"GPS",
			"Obsidian Horseshoe",
			"Obsidian Shield",
			"Tinkerers Workshop",
			"Cloud in a Balloon",
			"Adamantite Headgear",
			"Adamantite Helmet",
			"Adamantite Mask",
			"Adamantite Breastplate",
			"Adamantite Leggings",
			"Spectre Boots",
			"Adamantite Glaive",
			"Toolbelt",
			"Pearlsand Block",
			"Pearlstone Block",
			"Mining Shirt",
			"Mining Pants",
			"Pearlstone Brick",
			"Iridescent Brick",
			"Mudstone Block",
			"Cobalt Brick",
			"Mythril Brick",
			"Pearlstone Brick Wall",
			"Iridescent Brick Wall",
			"Mudstone Brick Wall",
			"Cobalt Brick Wall",
			"Mythril Brick Wall",
			"Holy Water",
			"Unholy Water",
			"Silt Block",
			"Fairy Bell",
			"Breaker Blade",
			"Blue Torch",
			"Red Torch",
			"Green Torch",
			"Purple Torch",
			"White Torch",
			"Yellow Torch",
			"Demon Torch",
			"Clockwork Assault Rifle",
			"Cobalt Repeater",
			"Mythril Repeater",
			"Dual Hook",
			"Star Statue",
			"Sword Statue",
			"Slime Statue",
			"Goblin Statue",
			"Shield Statue",
			"Bat Statue",
			"Fish Statue",
			"Bunny Statue",
			"Skeleton Statue",
			"Reaper Statue",
			"Woman Statue",
			"Imp Statue",
			"Gargoyle Statue",
			"Gloom Statue",
			"Hornet Statue",
			"Bomb Statue",
			"Crab Statue",
			"Hammer Statue",
			"Potion Statue",
			"Spear Statue",
			"Cross Statue",
			"Jellyfish Statue",
			"Bow Statue",
			"Boomerang Statue",
			"Boot Statue",
			"Chest Statue",
			"Bird Statue",
			"Axe Statue",
			"Corrupt Statue",
			"Tree Statue",
			"Anvil Statue",
			"Pickaxe Statue",
			"Mushroom Statue",
			"Eyeball Statue",
			"Pillar Statue",
			"Heart Statue",
			"Pot Statue",
			"Sunflower Statue",
			"King Statue",
			"Queen Statue",
			"Piranha Statue",
			"Planked Wall",
			"Wooden Beam",
			"Adamantite Repeater",
			"Adamantite Sword",
			"Cobalt Sword",
			"Mythril Sword",
			"Moon Charm",
			"Ruler",
			"Crystal Ball",
			"Disco Ball",
			"Sorcerer Emblem",
			"Warrior Emblem",
			"Ranger Emblem",
			"Demon Wings",
			"Angel Wings",
			"Magical Harp",
			"Rainbow Rod",
			"Ice Rod",
			"Neptune's Shell",
			"Mannequin",
			"Greater Healing Potion",
			"Greater Mana Potion",
			"Pixie Dust",
			"Crystal Shard",
			"Clown Hat",
			"Clown Shirt",
			"Clown Pants",
			"Flamethrower",
			"Bell",
			"Harp",
			"Wrench",
			"Wire Cutter",
			"Active Stone Block",
			"Inactive Stone Block",
			"Lever",
			"Laser Rifle",
			"Crystal Bullet",
			"Holy Arrow",
			"Magic Dagger",
			"Crystal Storm",
			"Cursed Flames",
			"Soul of Light",
			"Soul of Night",
			"Cursed Flame",
			"Cursed Torch",
			"Adamantite Forge",
			"Mythril Anvil",
			"Unicorn Horn",
			"Dark Shard",
			"Light Shard",
			"Red Pressure Plate",
			"Wire",
			"Spell Tome",
			"Star Cloak",
			"Megashark",
			"Shotgun",
			"Philosopher's Stone",
			"Titan Glove",
			"Cobalt Naginata",
			"Switch",
			"Dart Trap",
			"Boulder",
			"Green Pressure Plate",
			"Gray Pressure Plate",
			"Brown Pressure Plate",
			"Mechanical Eye",
			"Cursed Arrow",
			"Cursed Bullet",
			"Soul of Fright",
			"Soul of Might",
			"Soul of Sight",
			"Gungnir",
			"Hallowed Plate Mail",
			"Hallowed Greaves",
			"Hallowed Helmet",
			"Cross Necklace",
			"Mana Flower",
			"Mechanical Worm",
			"Mechanical Skull",
			"Hallowed Headgear",
			"Hallowed Mask",
			"Slime Crown",
			"Light Disc",
			"Music Box (Overworld Day)",
			"Music Box (Eerie)",
			"Music Box (Night)",
			"Music Box (Title)",
			"Music Box (Underground)",
			"Music Box (Boss1)",
			"Music Box (Jungle)",
			"Music Box (Corruption)",
			"Music Box (Underground Corruption)",
			"Music Box (The Hallow)",
			"Music Box (Boss2)",
			"Music Box (Underground Hallow)",
			"Music Box (Boss3)",
			"Soul of Flight",
			"Music Box",
			"Demonite Brick",
			"Hallowed Repeater",
			"Drax",
			"Explosives",
			"Inlet Pump",
			"Outlet Pump",
			"Timer1Second",
			"Timer3Second",
			"Timer5Second",
			"Candy Cane Block",
			"Candy Cane Wall",
			"Santa Hat",
			"Santa Shirt",
			"Santa Pants",
			"Green Candy Cane Block",
			"Green Candy Cane Wall",
			"Snow Block",
			"Snow Brick",
			"Snow Brick Wall",
			"Blue Light",
			"Red Light",
			"Green Light",
			"Blue Present",
			"Green Present",
			"Yellow Present",
			"Snow Globe",
			"Carrot",
			"Adamantite Beam",
			"Adamantite Beam Wall",
			"Demonite Brick Wall",
			"Sandstone Brick",
			"Sandstone Brick Wall",
			"Ebonstone Brick",
			"Ebonstone Brick Wall",
			"Red Stucco",
			"Yellow Stucco",
			"Green Stucco",
			"Gray Stucco",
			"Red Stucco Wall",
			"Yellow Stucco Wall",
			"Green Stucco Wall",
			"Gray Stucco Wall",
			"Ebonwood",
			"Rich Mahogany",
			"Pearlwood",
			"Ebonwood Wall",
			"Rich Mahogany Wall",
			"Pearlwood Wall",
			"Ebonwood Chest",
			"Rich Mahogany Chest",
			"Pearlwood Chest",
			"Ebonwood Chair",
			"Rich Mahogany Chair",
			"Pearlwood Chair",
			"Ebonwood Platform",
			"Rich Mahogany Platform",
			"Pearlwood Platform",
			"Bone Platform",
			"Ebonwood Work Bench",
			"Rich Mahogany Work Bench",
			"Pearlwood Work Bench",
			"Ebonwood Table",
			"Rich Mahogany Table",
			"Pearlwood Table",
			"Ebonwood Piano",
			"Rich Mahogany Piano",
			"Pearlwood Piano",
			"Ebonwood Bed",
			"Rich Mahogany Bed",
			"Pearlwood Bed",
			"Ebonwood Dresser",
			"Rich Mahogany Dresser",
			"Pearlwood Dresser",
			"Ebonwood Door",
			"Rich Mahogany Door",
			"Pearlwood Door",
			"Ebonwood Sword",
			"Ebonwood Hammer",
			"Ebonwood Bow",
			"Rich Mahogany Sword",
			"Rich Mahogany Hammer",
			"Rich Mahogany Bow",
			"Pearlwood Sword",
			"Pearlwood Hammer",
			"Pearlwood Bow",
			"Rainbow Brick",
			"Rainbow Brick Wall",
			"Ice Block",
			"Red's Wings",
			"Red's Helmet",
			"Red's Breastplate",
			"Red's Leggings",
			"Fish",
			"Ice Boomerang",
			"Keybrand",
			"Cutlass",
			"Boreal Wood Work Bench",
			"True Excalibur",
			"True Nights Edge",
			"Frostbrand",
			"Boreal Wood Table",
			"Red Potion",
			"Tactical Shotgun",
			"Ivy Chest",
			"Ice Chest",
			"Marrow",
			"Unholy Trident",
			"Frost Helmet",
			"Frost Breastplate",
			"Frost Leggings",
			"Tin Helmet",
			"Tin Chainmail",
			"Tin Greaves",
			"Lead Helmet",
			"Lead Chainmail",
			"Lead Greaves",
			"Tungsten Helmet",
			"Tungsten Chainmail",
			"Tungsten Greaves",
			"Platinum Helmet",
			"Platinum Chainmail",
			"Platinum Greaves",
			"Tin Ore",
			"Lead Ore",
			"Tungsten Ore",
			"Platinum Ore",
			"Tin Bar",
			"Lead Bar",
			"Tungsten Bar",
			"Platinum Bar",
			"Tin Watch",
			"Tungsten Watch",
			"Platinum Watch",
			"Tin Chandelier",
			"Tungsten Chandelier",
			"Platinum Chandelier",
			"Platinum Candle",
			"Platinum Candelabra",
			"Platinum Crown",
			"Lead Anvil",
			"Tin Brick",
			"Tungsten Brick",
			"Platinum Brick",
			"Tin Brick Wall",
			"Tungsten Brick Wall",
			"Platinum Brick Wall",
			"Beam Sword",
			"Ice Blade",
			"Ice Bow",
			"Frost Staff",
			"Wood Helmet",
			"Wood Breastplate",
			"Wood Greaves",
			"Ebonwood Helmet",
			"Ebonwood Breastplate",
			"Ebonwood Greaves",
			"Rich Mahogany Helmet",
			"Rich Mahogany Breastplate",
			"Rich Mahogany Greaves",
			"Pearlwood Helmet",
			"Pearlwood Breastplate",
			"Pearlwood Greaves",
			"Amethyst Staff",
			"Topaz Staff",
			"Sapphire Staff",
			"Emerald Staff",
			"Ruby Staff",
			"Diamond Staff",
			"Grass Wall",
			"Jungle Wall",
			"Flower Wall",
			"Jetpack",
			"Butterfly Wings",
			"Cactus Wall",
			"Cloud",
			"Cloud Wall",
			"Seaweed",
			"Rune Hat",
			"Rune Robe",
			"Mushroom Spear",
			"Terra Blade",
			"Grenade Launcher",
			"Rocket Launcher",
			"Proximity Mine Launcher",
			"Fairy Wings",
			"Slime Block",
			"Flesh Block",
			"Mushroom Wall",
			"Rain Cloud",
			"Bone Block",
			"Frozen Slime Block",
			"Bone Block Wall",
			"Slime Block Wall",
			"Flesh Block Wall",
			"Rocket I",
			"Rocket II",
			"Rocket III",
			"Rocket IV",
			"Asphalt Block",
			"Cobalt Pickaxe",
			"Mythril Pickaxe",
			"Adamantite Pickaxe",
			"Clentaminator",
			"Green Solution",
			"Blue Solution",
			"Purple Solution",
			"Dark Blue Solution",
			"Red Solution",
			"Harpy Wings",
			"Bone Wings",
			"Hammush",
			"Nettle Burst",
			"Ankh Banner",
			"Snake Banner",
			"Omega Banner",
			"Crimson Helmet",
			"Crimson Scalemail",
			"Crimson Greaves",
			"Blood Butcherer",
			"Tendon Bow",
			"Flesh Grinder",
			"Deathbringer Pickaxe",
			"Blood Lust Cluster",
			"The Undertaker",
			"The Meatball",
			"The Rotted Fork",
			"Eskimo Hood",
			"Eskimo Coat",
			"Eskimo Pants",
			"Living Wood Chair",
			"Cactus Chair",
			"Bone Chair",
			"Flesh Chair",
			"Mushroom Chair",
			"Bone Work Bench",
			"Cactus Work Bench",
			"Flesh Work Bench",
			"Mushroom Work Bench",
			"Slime Work Bench",
			"Cactus Door",
			"Flesh Door",
			"Mushroom Door",
			"Living Wood Door",
			"Bone Door",
			"Flame Wings",
			"Frozen Wings",
			"Ghost Wings",
			"Sunplate Block",
			"Disc Wall",
			"Skyware Chair",
			"Bone Table",
			"Flesh Table",
			"Living Wood Table",
			"Skyware Table",
			"Living Wood Chest",
			"Living Wood Wand",
			"Purple Ice Block",
			"Pink Ice Block",
			"Red Ice Block",
			"Crimstone Block",
			"Skyware Door",
			"Skyware Chest",
			"Steampunk Hat",
			"Steampunk Shirt",
			"Steampunk Pants",
			"Bee Hat",
			"Bee Shirt",
			"Bee Pants",
			"World Banner",
			"Sun Banner",
			"Gravity Banner",
			"Pharaohs Mask",
			"Actuator",
			"Blue Wrench",
			"Green Wrench",
			"Blue Pressure Plate",
			"Yellow Pressure Plate",
			"Discount Card",
			"Lucky Coin",
			"Unicornona Stick",
			"Sandstorm in a Bottle",
			"Boreal Wood Sofa",
			"Beach Ball",
			"Charm Of Myths",
			"Moon Shell",
			"Star Veil",
			"Water Walking Boots",
			"Tiara",
			"Princess Dress",
			"Pharaohs Robe",
			"Green Cap",
			"Mushroom Cap",
			"Tam OShanter",
			"Mummy Mask",
			"Mummy Shirt",
			"Mummy Pants",
			"Cowboy Hat",
			"Cowboy Jacket",
			"Cowboy Pants",
			"Pirate Hat",
			"Pirate Shirt",
			"Pirate Pants",
			"Viking Helmet",
			"Crimtane Ore",
			"Cactus Sword",
			"Cactus Pickaxe",
			"Ice Brick",
			"Ice Brick Wall",
			"Adhesive Bandage",
			"Armor Polish",
			"Bezoar",
			"Blindfold",
			"Fast Clock",
			"Megaphone",
			"Nazar",
			"Vitamins",
			"Trifold Map",
			"Cactus Helmet",
			"Cactus Breastplate",
			"Cactus Leggings",
			"Power Glove",
			"Lightning Boots",
			"Sun Stone",
			"Moon Stone",
			"Armor Bracing",
			"Medicated Bandage",
			"The Plan",
			"Countercurse Mantra",
			"Coin Gun",
			"Lava Charm",
			"Obsidian Water Walking Boots",
			"Lava Waders",
			"Pure Water Fountain",
			"Desert Water Fountain",
			"Shadewood",
			"Shadewood Door",
			"Shadewood Platform",
			"Shadewood Chest",
			"Shadewood Chair",
			"Shadewood Work Bench",
			"Shadewood Table",
			"Shadewood Dresser",
			"Shadewood Piano",
			"Shadewood Bed",
			"Shadewood Sword",
			"Shadewood Hammer",
			"Shadewood Bow",
			"Shadewood Helmet",
			"Shadewood Breastplate",
			"Shadewood Greaves",
			"Shadewood Wall",
			"Cannon",
			"Cannonball",
			"Flare Gun",
			"Flare",
			"Bone Wand",
			"Leaf Wand",
			"Flying Carpet",
			"Avenger Emblem",
			"Mechanical Glove",
			"Land Mine",
			"Paladin's Shield",
			"Web Slinger",
			"Jungle Water Fountain",
			"Icy Water Fountain",
			"Corrupt Water Fountain",
			"Crimson Water Fountain",
			"Hallowed Water Fountain",
			"Blood Water Fountain",
			"Umbrella",
			"Chlorophyte Ore",
			"Steampunk Wings",
			"Snowball",
			"Ice Skates",
			"Snowball Launcher",
			"Web Covered Chest",
			"Climbing Claws",
			"Ancient Iron Helmet",
			"Ancient Gold Helmet",
			"Ancient Shadow Helmet",
			"Ancient Shadow Scalemail",
			"Ancient Shadow Greaves",
			"Ancient Necro Helmet",
			"Ancient Cobalt Helmet",
			"Ancient Cobalt Breastplate",
			"Ancient Cobalt Leggings",
			"Black Belt",
			"Boomstick",
			"Rope",
			"Campfire",
			"Marshmallow",
			"Marshmallowona Stick",
			"Cooked Marshmallow",
			"Red Rocket",
			"Green Rocket",
			"Blue Rocket",
			"Yellow Rocket",
			"Ice Torch",
			"Shoe Spikes",
			"Tiger Climbing Gear",
			"Tabi",
			"Pink Eskimo Hood",
			"Pink Eskimo Coat",
			"Pink Eskimo Pants",
			"Pink Thread",
			"Mana Regeneration Band",
			"Sandstorm in a Balloon",
			"Master Ninja Gear",
			"Rope Coil",
			"Blowgun",
			"Blizzard in a Bottle",
			"Frostburn Arrow",
			"Enchanted Sword",
			"Pickaxe Axe",
			"Cobalt Waraxe",
			"Mythril Waraxe",
			"Adamantite Waraxe",
			"Eaters Bone",
			"Blend OMatic",
			"Meat Grinder",
			"Extractinator",
			"Solidifier",
			"Amber",
			"Confetti Gun",
			"Chlorophyte Mask",
			"Chlorophyte Helmet",
			"Chlorophyte Headgear",
			"Chlorophyte Plate Mail",
			"Chlorophyte Greaves",
			"Chlorophyte Bar",
			"Red Dye",
			"Orange Dye",
			"Yellow Dye",
			"Lime Dye",
			"Green Dye",
			"Teal Dye",
			"Cyan Dye",
			"Sky Blue Dye",
			"Blue Dye",
			"Purple Dye",
			"Violet Dye",
			"Pink Dye",
			"Redand Black Dye",
			"Orange and Black Dye",
			"Yellow and Black Dye",
			"Lime and Black Dye",
			"Green and Black Dye",
			"Teal and Black Dye",
			"Cyan and Black Dye",
			"Sky Blue and Black Dye",
			"Blueand Black Dye",
			"Purple and Black Dye",
			"Violet and Black Dye",
			"Pink and Black Dye",
			"Flame Dye",
			"Flame and Black Dye",
			"Green Flame Dye",
			"Green Flame and Black Dye",
			"Blue Flame Dye",
			"Blue Flame and Black Dye",
			"Silver Dye",
			"Bright Red Dye",
			"Bright Orange Dye",
			"Bright Yellow Dye",
			"Bright Lime Dye",
			"Bright Green Dye",
			"Bright Teal Dye",
			"Bright Cyan Dye",
			"Bright Sky Blue Dye",
			"Bright Blue Dye",
			"Bright Purple Dye",
			"Bright Violet Dye",
			"Bright Pink Dye",
			"Black Dye",
			"Red and Silver Dye",
			"Orange and Silver Dye",
			"Yellow and Silver Dye",
			"Lime and Silver Dye",
			"Green and Silver Dye",
			"Teal and Silver Dye",
			"Cyan and Silver Dye",
			"Sky Blue and Silver Dye",
			"Blue and Silver Dye",
			"Purple and Silver Dye",
			"Violet and Silver Dye",
			"Pinkand Silver Dye",
			"Intense Flame Dye",
			"Intense Green Flame Dye",
			"Intense Blue Flame Dye",
			"Rainbow Dye",
			"Intense Rainbow Dye",
			"Yellow Gradient Dye",
			"Cyan Gradient Dye",
			"Violet Gradient Dye",
			"Paintbrush",
			"Paint Roller",
			"Red Paint",
			"Orange Paint",
			"Yellow Paint",
			"Lime Paint",
			"Green Paint",
			"Teal Paint",
			"Cyan Paint",
			"Sky Blue Paint",
			"Blue Paint",
			"Purple Paint",
			"Violet Paint",
			"Pink Paint",
			"Deep Red Paint",
			"Deep Orange Paint",
			"Deep Yellow Paint",
			"Deep Lime Paint",
			"Deep Green Paint",
			"Deep Teal Paint",
			"Deep Cyan Paint",
			"Deep Sky Blue Paint",
			"Deep Blue Paint",
			"Deep Purple Paint",
			"Deep Violet Paint",
			"Deep Pink Paint",
			"Black Paint",
			"White Paint",
			"Gray Paint",
			"Paint Scraper",
			"Lihzahrd Brick",
			"Lihzahrd Brick Wall",
			"Slush Block",
			"Palladium Ore",
			"Orichalcum Ore",
			"Titanium Ore",
			"Teal Mushroom",
			"Green Mushroom",
			"Sky Blue Flower",
			"Yellow Marigold",
			"Blue Berries",
			"Lime Kelp",
			"Pink Prickly Pear",
			"Orange Bloodroot",
			"Red Husk",
			"Cyan Husk",
			"Violet Husk",
			"Purple Mucos",
			"Black Ink",
			"Dye Vat",
			"Bee Gun",
			"Possessed Hatchet",
			"Bee Keeper",
			"Hive",
			"Honey Block",
			"Hive Wall",
			"Crispy Honey Block",
			"Honey Bucket",
			"Hive Wand",
			"Beenade",
			"Gravity Globe",
			"Honey Comb",
			"Abeemination",
			"Bottled Honey",
			"Rain Hat",
			"Rain Coat",
			"Lihzahrd Door",
			"Dungeon Door",
			"Lead Door",
			"Iron Door",
			"Temple Key",
			"Lihzahrd Chest",
			"Lihzahrd Chair",
			"Lihzahrd Table",
			"Lihzahrd Work Bench",
			"Super Dart Trap",
			"Flame Trap",
			"Spiky Ball Trap",
			"Spear Trap",
			"Wooden Spike",
			"Lihzahrd Pressure Plate",
			"Lihzahrd Statue",
			"Lihzahrd Watcher Statue",
			"Lihzahrd Guardian Statue",
			"Wasp Gun",
			"Piranha Gun",
			"Pygmy Staff",
			"Pygmy Necklace",
			"Tiki Mask",
			"Tiki Shirt",
			"Tiki Pants",
			"Leaf Wings",
			"Blizzard in a Balloon",
			"Bundle Of Balloons",
			"Bat Wings",
			"Bone Sword",
			"Hercules Beetle",
			"Smoke Bomb",
			"Bone Key",
			"Nectar",
			"Tiki Totem",
			"Lizard Egg",
			"Grave Marker",
			"Cross Grave Marker",
			"Headstone",
			"Gravestone",
			"Obelisk",
			"Leaf Blower",
			"Chlorophyte Bullet",
			"Parrot Cracker",
			"Strange Glowing Mushroom",
			"Seedling",
			"Wisp in a Bottle",
			"Palladium Bar",
			"Palladium Sword",
			"Palladium Pike",
			"Palladium Repeater",
			"Palladium Pickaxe",
			"Palladium Drill",
			"Palladium Chainsaw",
			"Orichalcum Bar",
			"Orichalcum Sword",
			"Orichalcum Halberd",
			"Orichalcum Repeater",
			"Orichalcum Pickaxe",
			"Orichalcum Drill",
			"Orichalcum Chainsaw",
			"Titanium Bar",
			"Titanium Sword",
			"Titanium Trident",
			"Titanium Repeater",
			"Titanium Pickaxe",
			"Titanium Drill",
			"Titanium Chainsaw",
			"Palladium Mask",
			"Palladium Helmet",
			"Palladium Headgear",
			"Palladium Breastplate",
			"Palladium Leggings",
			"Orichalcum Mask",
			"Orichalcum Helmet",
			"Orichalcum Headgear",
			"Orichalcum Breastplate",
			"Orichalcum Leggings",
			"Titanium Mask",
			"Titanium Helmet",
			"Titanium Headgear",
			"Titanium Breastplate",
			"Titanium Leggings",
			"Orichalcum Anvil",
			"Titanium Forge",
			"Palladium Waraxe",
			"Orichalcum Waraxe",
			"Titanium Waraxe",
			"Hallowed Bar",
			"Chlorophyte Claymore",
			"Chlorophyte Saber",
			"Chlorophyte Partisan",
			"Chlorophyte Shotbow",
			"Chlorophyte Pickaxe",
			"Chlorophyte Drill",
			"Chlorophyte Chainsaw",
			"Chlorophyte Greataxe",
			"Chlorophyte Warhammer",
			"Chlorophyte Arrow",
			"Amethyst Hook",
			"Topaz Hook",
			"Sapphire Hook",
			"Emerald Hook",
			"Ruby Hook",
			"Diamond Hook",
			"Amber Mosquito",
			"Umbrella Hat",
			"Nimbus Rod",
			"Orange Torch",
			"Crimsand Block",
			"Bee Cloak",
			"Eye Of The Golem",
			"Honey Balloon",
			"Blue Horseshoe Balloon",
			"White Horseshoe Balloon",
			"Yellow Horseshoe Balloon",
			"Frozen Turtle Shell",
			"Sniper Rifle",
			"Venus Magnum",
			"Crimson Rod",
			"Crimtane Bar",
			"Stynger",
			"Flower Pow",
			"Rainbow Gun",
			"Stynger Bolt",
			"Chlorophyte Jackhammer",
			"Teleporter",
			"Flower of Frost",
			"Uzi",
			"Magnet Sphere",
			"Purple Stained Glass",
			"Yellow Stained Glass",
			"Blue Stained Glass",
			"Green Stained Glass",
			"Red Stained Glass",
			"Multicolored Stained Glass",
			"Skeletron Hand",
			"Skull",
			"Balla Hat",
			"Gangsta Hat",
			"Sailor Hat",
			"Eye Patch",
			"Sailor Shirt",
			"Sailor Pants",
			"Skeletron Mask",
			"Amethyst Robe",
			"Topaz Robe",
			"Sapphire Robe",
			"Emerald Robe",
			"Ruby Robe",
			"Diamond Robe",
			"White Tuxedo Shirt",
			"White Tuxedo Pants",
			"Panic Necklace",
			"Life Fruit",
			"Lihzahrd Altar",
			"Lihzahrd Power Cell",
			"Picksaw",
			"Heat Ray",
			"Staff of Earth",
			"Golem Fist",
			"Water Chest",
			"Binoculars",
			"Rifle Scope",
			"Destroyer Emblem",
			"High Velocity Bullet",
			"Jellyfish Necklace",
			"Zombie Arm",
			"The Axe",
			"Ice Sickle",
			"Clothier Voodoo Doll",
			"Poison Staff",
			"Slime Staff",
			"Poison Dart",
			"Eye Spring",
			"Toy Sled",
			"Book of Skulls",
			"KOCannon",
			"Pirate Map",
			"Turtle Helmet",
			"Turtle Scale Mail",
			"Turtle Leggings",
			"Snowball Cannon",
			"Bone Pickaxe",
			"Magic Quiver",
			"Magma Stone",
			"Obsidian Rose",
			"Bananarang",
			"Chain Knife",
			"Rod of Discord",
			"Death Sickle",
			"Turtle Shell",
			"Tissue Sample",
			"Vertebrae",
			"Bloody Spine",
			"Ichor",
			"Ichor Torch",
			"Ichor Arrow",
			"Ichor Bullet",
			"Golden Shower",
			"Bunny Cannon",
			"Explosive Bunny",
			"Vial of Venom",
			"Flask of Venom",
			"Venom Arrow",
			"Venom Bullet",
			"Fire Gauntlet",
			"Cog",
			"Confetti",
			"Nanites",
			"Explosive Powder",
			"Gold Dust",
			"Party Bullet",
			"Nano Bullet",
			"Exploding Bullet",
			"Golden Bullet",
			"Flask of Cursed Flames",
			"Flask of Fire",
			"Flask of Gold",
			"Flask of Ichor",
			"Flask of Nanites",
			"Flask of Party",
			"Flask of Poison",
			"Eye of Cthulhu Trophy",
			"Eater of Worlds Trophy",
			"Brain of Cthulhu Trophy",
			"Skeletron Trophy",
			"Queen Bee Trophy",
			"Wall of Flesh Trophy",
			"Destroyer Trophy",
			"Skeletron Prime Trophy",
			"Retinazer Trophy",
			"Spazmatism Trophy",
			"Plantera Trophy",
			"Golem Trophy",
			"Blood Moon Rising",
			"The Hanged Man",
			"Glory Of The Fire",
			"Bone Warp",
			"Wall Skeleton",
			"Hanging Skeleton",
			"Blue Slab Wall",
			"Blue Tiled Wall",
			"Pink Slab Wall",
			"Pink Tiled Wall",
			"Green Slab Wall",
			"Green Tiled Wall",
			"Blue Brick Platform",
			"Pink Brick Platform",
			"Green Brick Platform",
			"Metal Shelf",
			"Brass Shelf",
			"Wood Shelf",
			"Brass Lantern",
			"Caged Lantern",
			"Carriage Lantern",
			"Alchemy Lantern",
			"Diablost Lamp",
			"Oil Rag Sconse",
			"Blue Dungeon Chair",
			"Blue Dungeon Table",
			"Blue Dungeon Work Bench",
			"Green Dungeon Chair",
			"Green Dungeon Table",
			"Green Dungeon Work Bench",
			"Pink Dungeon Chair",
			"Pink Dungeon Table",
			"Pink Dungeon Work Bench",
			"Blue Dungeon Candle",
			"Green Dungeon Candle",
			"Pink Dungeon Candle",
			"Blue Dungeon Vase",
			"Green Dungeon Vase",
			"Pink Dungeon Vase",
			"Blue Dungeon Door",
			"Green Dungeon Door",
			"Pink Dungeon Door",
			"Blue Dungeon Bookcase",
			"Green Dungeon Bookcase",
			"Pink Dungeon Bookcase",
			"Catacomb",
			"Dungeon Shelf",
			"Skellington J Skellingsworth",
			"The Cursed Man",
			"The Eye Sees the End",
			"Something Evil is Watching You",
			"The Twins Have Awoken",
			"The Screamer",
			"Goblins Playing Poker",
			"Dryadisque",
			"Sunflowers",
			"Terrarian Gothic",
			"Beanie",
			"Imbuing Station",
			"Star in a Bottle",
			"Empty Bullet",
			"Impact",
			"Powered by Birds",
			"The Destroyer",
			"The Persistency of Eyes",
			"Unicorn Crossing the Hallows",
			"Great Wave",
			"Starry Night",
			"Guide Picasso",
			"The Guardians Gaze",
			"Father of Someone",
			"Nurse Lisa",
			"Shadowbeam Staff",
			"Inferno Fork",
			"Spectre Staff",
			"Wooden Fence",
			"Lead Fence",
			"Bubble Machine",
			"Bubble Wand",
			"Marching Bones Banner",
			"Necromantic Sign",
			"Rusted Company Standard",
			"Ragged Brotherhood Sigil",
			"Molten Legion Flag",
			"Diabolic Sigil",
			"Obsidian Platform",
			"Obsidian Door",
			"Obsidian Chair",
			"Obsidian Table",
			"Obsidian Work Bench",
			"Obsidian Vase",
			"Obsidian Bookcase",
			"Hellbound Banner",
			"Hell Hammer Banner",
			"Helltower Banner",
			"Lost Hopes of Man Banner",
			"Obsidian Watcher Banner",
			"Lava Erupts Banner",
			"Blue Dungeon Bed",
			"Green Dungeon Bed",
			"Pink Dungeon Bed",
			"Obsidian Bed",
			"Waldo",
			"Darkness",
			"Dark Soul Reaper",
			"Land",
			"Trapped Ghost",
			"Demons Eye",
			"Finding Gold",
			"First Encounter",
			"Good Morning",
			"Underground Reward",
			"Throughthe Window",
			"Place Abovethe Clouds",
			"Do Not Steponthe Grass",
			"Cold Watersinthe White Land",
			"Lightless Chasms",
			"The Land of Deceiving Looks",
			"Daylight",
			"Secret of the Sands",
			"Deadland Comes Alive",
			"Evil Presence",
			"Sky Guardian",
			"American Explosive",
			"Discover",
			"Hand Earth",
			"Old Miner",
			"Skelehead",
			"Facingthe Cerebral Mastermind",
			"Lake of Fire",
			"Trio Super Heroes",
			"Spectre Hood",
			"Spectre Robe",
			"Spectre Pants",
			"Spectre Pickaxe",
			"Spectre Hamaxe",
			"Ectoplasm",
			"Gothic Chair",
			"Gothic Table",
			"Gothic Work Bench",
			"Gothic Bookcase",
			"Paladin's Hammer",
			"SWAT Helmet",
			"Bee Wings",
			"Giant Harpy Feather",
			"Bone Feather",
			"Fire Feather",
			"Ice Feather",
			"Broken Bat Wing",
			"Tattered Bee Wing",
			"Large Amethyst",
			"Large Topaz",
			"Large Sapphire",
			"Large Emerald",
			"Large Ruby",
			"Large Diamond",
			"Jungle Chest",
			"Corruption Chest",
			"Crimson Chest",
			"Hallowed Chest",
			"Frozen Chest",
			"Jungle Key",
			"Corruption Key",
			"Crimson Key",
			"Hallowed Key",
			"Frozen Key",
			"Imp Face",
			"Ominous Presence",
			"Shining Moon",
			"Living Gore",
			"Flowing Magma",
			"Spectre Paintbrush",
			"Spectre Paint Roller",
			"Spectre Paint Scraper",
			"Shroomite Headgear",
			"Shroomite Mask",
			"Shroomite Helmet",
			"Shroomite Breastplate",
			"Shroomite Leggings",
			"Autohammer",
			"Shroomite Bar",
			"SDMG",
			"Cenx's Tiara",
			"Cenx's Breastplate",
			"Cenx's Leggings",
			"Crowno's Mask",
			"Crowno's Breastplate",
			"Crowno's Leggings",
			"Will's Helmet",
			"Will's Breastplate",
			"Will's Leggings",
			"Jim's Helmet",
			"Jim's Breastplate",
			"Jim's Leggings",
			"Aaron's Helmet",
			"Aaron's Breastplate",
			"Aaron's Leggings",
			"Vampire Knives",
			"Broken Hero Sword",
			"Scourge of the Corruptor",
			"Staff of the Frost Hydra",
			"The Creation of the Guide",
			"The Merchant",
			"Crowno Devours His Lunch",
			"Rare Enchantment",
			"Glorious Night",
			"Sweetheart Necklace",
			"Flurry Boots",
			"D-Town's Helmet",
			"D-Town's Breastplate",
			"D-Town's Leggings",
			"D-Town's Wings",
			"Will's Wings",
			"Crowno's Wings",
			"Cenx's Wings",
			"Cenx's Dress",
			"Cenx's Dress Pants",
			"Palladium Column",
			"Palladium Column Wall",
			"Bubblegum Block",
			"Bubblegum Block Wall",
			"Titanstone Block",
			"Titanstone Block Wall",
			"Magic Cuffs",
			"Music Box (Snow)",
			"Music Box (Space)",
			"Music Box (Crimson)",
			"Music Box (Boss4)",
			"Music Box (Alt Overworld Day)",
			"Music Box (Rain)",
			"Music Box (Ice)",
			"Music Box (Desert)",
			"Music Box (Ocean)",
			"Music Box (Dungeon)",
			"Music Box (Plantera)",
			"Music Box (Boss5)",
			"Music Box (Temple)",
			"Music Box (Eclipse)",
			"Music Box (Mushrooms)",
			"Butterfly Dust",
			"Ankh Charm",
			"Ankh Shield",
			"Blue Flare",
			"Angler Fish Banner",
			"Angry Nimbus Banner",
			"Anomura Fungus Banner",
			"Antlion Banner",
			"Arapaima Banner",
			"Armored Skeleton Banner",
			"Bat Banner",
			"Bird Banner",
			"Black Recluse Banner",
			"Blood Feeder Banner",
			"Blood Jelly Banner",
			"Blood Crawler Banner",
			"Bone Serpent Banner",
			"Bunny Banner",
			"Chaos Elemental Banner",
			"Mimic Banner",
			"Clown Banner",
			"Corrupt Bunny Banner",
			"Corrupt Goldfish Banner",
			"Crab Banner",
			"Crimera Banner",
			"Crimson Axe Banner",
			"Cursed Hammer Banner",
			"Demon Banner",
			"Demon Eye Banner",
			"Derpling Banner",
			"Eater of Souls Banner",
			"Enchanted Sword Banner",
			"Zombie Eskimo Banner",
			"Face Monster Banner",
			"Floaty Gross Banner",
			"Flying Fish Banner",
			"Flying Snake Banner",
			"Frankenstein Banner",
			"Fungi Bulb Banner",
			"Fungo Fish Banner",
			"Gastropod Banner",
			"Goblin Archer Banner",
			"Goblin Sorcerer Banner",
			"Goblin Scout Banner",
			"Goblin Thief Banner",
			"Goblin Warrior Banner",
			"Goldfish Banner",
			"Harpy Banner",
			"Hellbat Banner",
			"Herpling Banner",
			"Hornet Banner",
			"Ice Elemental Banner",
			"Icy Merman Banner",
			"Fire Imp Banner",
			"Jellyfish Banner",
			"Jungle Creeper Banner",
			"Lihzahrd Banner",
			"Man Eater Banner",
			"Meteor Head Banner",
			"Moth Banner",
			"Mummy Banner",
			"Mushi Ladybug Banner",
			"Parrot Banner",
			"Pigron Banner",
			"Piranha Banner",
			"Pirate Banner",
			"Pixie Banner",
			"Raincoat Zombie Banner",
			"Reaper Banner",
			"Shark Banner",
			"Skeleton Banner",
			"Skeleton Mage Banner",
			"Slime Banner",
			"Snow Flinx Banner",
			"Spider Banner",
			"Spore Zombie Banner",
			"Swamp Thing Banner",
			"Tortoise Banner",
			"Toxic Sludge Banner",
			"Umbrella Slime Banner",
			"Unicorn Banner",
			"Vampire Banner",
			"Vulture Banner",
			"Nypmh Banner",
			"Werewolf Banner",
			"Wolf Banner",
			"World Feeder Banner",
			"Worm Banner",
			"Wraith Banner",
			"Wyvern Banner",
			"Zombie Banner",
			"Glass Platform",
			"Glass Chair",
			"Golden Chair",
			"Golden Toilet",
			"Bar Stool",
			"Honey Chair",
			"Steampunk Chair",
			"Glass Door",
			"Golden Door",
			"Honey Door",
			"Steampunk Door",
			"Glass Table",
			"Banquet Table",
			"Bar",
			"Golden Table",
			"Honey Table",
			"Steampunk Table",
			"Glass Bed",
			"Golden Bed",
			"Honey Bed",
			"Steampunk Bed",
			"Living Wood Wall",
			"Fart in a Jar",
			"Pumpkin",
			"Pumpkin Wall",
			"Hay",
			"Hay Wall",
			"Spooky Wood",
			"Spooky Wood Wall",
			"Pumpkin Helmet",
			"Pumpkin Breastplate",
			"Pumpkin Leggings",
			"Candy Apple",
			"Soul Cake",
			"Nurse Hat",
			"Nurse Shirt",
			"Nurse Pants",
			"Wizard's Hat",
			"Guy Fawkes Mask",
			"Dye Trader Robe",
			"Steampunk Goggles",
			"Cyborg Helmet",
			"Cyborg Shirt",
			"Cyborg Pants",
			"Creeper Mask",
			"Creeper Shirt",
			"Creeper Pants",
			"Cat Mask",
			"Cat Shirt",
			"Cat Pants",
			"Ghost Mask",
			"Ghost Shirt",
			"Pumpkin Mask",
			"Pumpkin Shirt",
			"Pumpkin Pants",
			"Robot Mask",
			"Robot Shirt",
			"Robot Pants",
			"Unicorn Mask",
			"Unicorn Shirt",
			"Unicorn Pants",
			"Vampire Mask",
			"Vampire Shirt",
			"Vampire Pants",
			"Witch Hat",
			"Leprechaun Hat",
			"Leprechaun Shirt",
			"Leprechaun Pants",
			"Pixie Shirt",
			"Pixie Pants",
			"Princess Hat",
			"Princess Dress New",
			"Goodie Bag",
			"Witch Dress",
			"Witch Boots",
			"Bride of Frankenstein Mask",
			"Bride of Frankenstein Dress",
			"Karate Tortoise Mask",
			"Karate Tortoise Shirt",
			"Karate Tortoise Pants",
			"Candy Corn Rifle",
			"Candy Corn",
			"Jack 'O Lantern Launcher",
			"Explosive Jack 'O Lantern",
			"Sickle",
			"Pumpkin Pie",
			"Scarecrow Hat",
			"Scarecrow Shirt",
			"Scarecrow Pants",
			"Cauldron",
			"Pumpkin Chair",
			"Pumpkin Door",
			"Pumpkin Table",
			"Pumpkin Work Bench",
			"Pumpkin Platform",
			"Tattered Fairy Wings",
			"Spider Egg",
			"Magical Pumpkin Seed",
			"Bat Hook",
			"Bat Scepter",
			"Raven Staff",
			"Jungle Key Mold",
			"Corruption Key Mold",
			"Crimson Key Mold",
			"Hallowed Key Mold",
			"Frozen Key Mold",
			"Hanging Jack OLantern",
			"Rotten Egg",
			"Unlucky Yarn",
			"Black Fairy Dust",
			"Jackelier",
			"Jack OLantern",
			"Spooky Chair",
			"Spooky Door",
			"Spooky Table",
			"Spooky Work Bench",
			"Spooky Platform",
			"Reaper Hood",
			"Reaper Robe",
			"Fox Mask",
			"Fox Shirt",
			"Fox Pants",
			"Cat Ears",
			"Bloody Machete",
			"The Horsemans Blade",
			"Bladed Glove",
			"Pumpkin Seed",
			"Spooky Hook",
			"Spooky Wings",
			"Spooky Twig",
			"Spooky Helmet",
			"Spooky Breastplate",
			"Spooky Leggings",
			"Stake Launcher",
			"Stake",
			"Cursed Sapling",
			"Space Creature Mask",
			"Space Creature Shirt",
			"Space Creature Pants",
			"Wolf Mask",
			"Wolf Shirt",
			"Wolf Pants",
			"Pumpkin Moon Medallion",
			"Necromantic Scroll",
			"Jacking Skeletron",
			"Bitter Harvest",
			"Blood Moon Countess",
			"Hallows Eve",
			"Morbid Curiosity",
			"Treasure Hunter Shirt",
			"Treasure Hunter Pants",
			"Dryad Coverings",
			"Dryad Loincloth",
			"Mourning Wood Trophy",
			"Pumpking Trophy",
			"Jack 'O Lantern Mask",
			"Sniper Scope",
			"Heart Lantern",
			"Jellyfish Diving Gear",
			"Arctic Diving Gear",
			"Frostspark Boots",
			"Fart In A Balloon",
			"Papyrus Scarab",
			"Celestial Stone",
			"Hoverboard",
			"Candy Cane",
			"Sugar Plum",
			"Present",
			"Red Ryder",
			"Festive Wings",
			"Pine Tree Block",
			"Christmas Tree",
			"Star Topper1",
			"Star Topper2",
			"Star Topper3",
			"Bow Topper",
			"White Garland",
			"White And Red Garland",
			"Red Gardland",
			"Red And Green Gardland",
			"Green Gardland",
			"Green And White Garland",
			"Multicolored Bulb",
			"Red Bulb",
			"Yellow Bulb",
			"Green Bulb",
			"Red And Green Bulb",
			"Yellow And Green Bulb",
			"Red And Yellow Bulb",
			"White Bulb",
			"White And Red Bulb",
			"White And Yellow Bulb",
			"White And Green Bulb",
			"Multicolored Lights",
			"Red Lights",
			"Green Lights",
			"Blue Lights",
			"Yellow Lights",
			"Red And Yellow Lights",
			"Red And Green Lights",
			"Yellow And Green Lights",
			"Blue And Green Lights",
			"Red And Blue Lights",
			"Blue And Yellow Lights",
			"Giant Bow",
			"Reindeer Antlers",
			"Holly",
			"Candy Cane Sword",
			"Eld Melter",
			"Christmas Pudding",
			"Eggnog",
			"Star Anise",
			"Reindeer Bells",
			"Candy Cane Hook",
			"Christmas Hook",
			"Candy Cane Pickaxe",
			"Fruitcake Chakram",
			"Sugar Cookie",
			"Gingerbread Cookie",
			"Hand Warmer",
			"Coal",
			"Toolbox",
			"Pine Door",
			"Pine Chair",
			"Pine Table",
			"Dog Whistle",
			"Christmas Tree Sword",
			"Chain Gun",
			"Razorpine",
			"Blizzard Staff",
			"Mrs. Clause Hat",
			"Mrs. Clause Shirt",
			"Mrs. Clause Heels",
			"Parka Hood",
			"Parka Coat",
			"Parka Pants",
			"Snow Hat",
			"Ugly Sweater",
			"Tree Mask",
			"Tree Shirt",
			"Tree Trunks",
			"Elf Hat",
			"Elf Shirt",
			"Elf Pants",
			"Snowman Cannon",
			"North Pole",
			"Christmas Tree Wallpaper",
			"Ornament Wallpaper",
			"Candy Cane Wallpaper",
			"Festive Wallpaper",
			"Stars Wallpaper",
			"Squiggles Wallpaper",
			"Snowflake Wallpaper",
			"Krampus Horn Wallpaper",
			"Bluegreen Wallpaper",
			"Grinch Finger Wallpaper",
			"Naughty Present",
			"Baby Grinch Mischief Whistle",
			"Ice Queen Trophy",
			"Santa NK1Trophy",
			"Everscream Trophy",
			"Music Box (Pumpkin Moon)",
			"Music Box (Alt Underground)",
			"Music Box (Frost Moon)",
			"Brown Paint",
			"Shadow Paint",
			"Negative Paint",
			"Team Dye",
			"Amethyst Gemspark Block",
			"Topaz Gemspark Block",
			"Sapphire Gemspark Block",
			"Emerald Gemspark Block",
			"Ruby Gemspark Block",
			"Diamond Gemspark Block",
			"Amber Gemspark Block",
			"Life Hair Dye",
			"Mana Hair Dye",
			"Depth Hair Dye",
			"Money Hair Dye",
			"Time Hair Dye",
			"Team Hair Dye",
			"Biome Hair Dye",
			"Party Hair Dye",
			"Rainbow Hair Dye",
			"Speed Hair Dye",
			"Angel Halo",
			"Fez",
			"Womannquin",
			"Hair Dye Remover",
			"Bug Net",
			"Firefly",
			"Firefly in a Bottle",
			"Monarch Butterfly",
			"Purple Emperor Butterfly",
			"Red Admiral Butterfly",
			"Ulysses Butterfly",
			"Sulphur Butterfly",
			"Tree Nymph Butterfly",
			"Zebra Swallowtail Butterfly",
			"Julia Butterfly",
			"Worm",
			"Mouse",
			"Lightning Bug",
			"Lightning Bug in a Bottle",
			"Snail",
			"Glowing Snail",
			"Fancy Grey Wallpaper",
			"Ice Floe Wallpaper",
			"Music Wallpaper",
			"Purple Rain Wallpaper",
			"Rainbow Wallpaper",
			"Sparkle Stone Wallpaper",
			"Starlit Heaven Wallpaper",
			"Bird",
			"Blue Jay",
			"Cardinal",
			"Squirrel",
			"Bunny",
			"Cactus Bookcase",
			"Ebonwood Bookcase",
			"Flesh Bookcase",
			"Honey Bookcase",
			"Steampunk Bookcase",
			"Glass Bookcase",
			"Rich Mahogany Bookcase",
			"Pearlwood Bookcase",
			"Spooky Bookcase",
			"Skyware Bookcase",
			"Lihzahrd Bookcase",
			"Frozen Bookcase",
			"Cactus Lantern",
			"Ebonwood Lantern",
			"Flesh Lantern",
			"Honey Lantern",
			"Steampunk Lantern",
			"Glass Lantern",
			"Rich Mahogany Lantern",
			"Pearlwood Lantern",
			"Frozen Lantern",
			"Lihzahrd Lantern",
			"Skyware Lantern",
			"Spooky Lantern",
			"Frozen Door",
			"Cactus Candle",
			"Ebonwood Candle",
			"Flesh Candle",
			"Glass Candle",
			"Frozen Candle",
			"Rich Mahogany Candle",
			"Pearlwood Candle",
			"Lihzahrd Candle",
			"Skyware Candle",
			"Pumpkin Candle",
			"Cactus Chandelier",
			"Ebonwood Chandelier",
			"Flesh Chandelier",
			"Honey Chandelier",
			"Frozen Chandelier",
			"Rich Mahogany Chandelier",
			"Pearlwood Chandelier",
			"Lihzahrd Chandelier",
			"Skyware Chandelier",
			"Spooky Chandelier",
			"Glass Chandelier",
			"Cactus Bed",
			"Flesh Bed",
			"Frozen Bed",
			"Lihzahrd Bed",
			"Skyware Bed",
			"Spooky Bed",
			"Cactus Bathtub",
			"Ebonwood Bathtub",
			"Flesh Bathtub",
			"Glass Bathtub",
			"Frozen Bathtub",
			"Rich Mahogany Bathtub",
			"Pearlwood Bathtub",
			"Lihzahrd Bathtub",
			"Skyware Bathtub",
			"Spooky Bathtub",
			"Cactus Lamp",
			"Ebonwood Lamp",
			"Flesh Lamp",
			"Glass Lamp",
			"Frozen Lamp",
			"Rich Mahogany Lamp",
			"Pearlwood Lamp",
			"Lihzahrd Lamp",
			"Skyware Lamp",
			"Spooky Lamp",
			"Cactus Candelabra",
			"Ebonwood Candelabra",
			"Flesh Candelabra",
			"Honey Candelabra",
			"Steampunk Candelabra",
			"Glass Candelabra",
			"Rich Mahogany Candelabra",
			"Pearlwood Candelabra",
			"Frozen Candelabra",
			"Lihzahrd Candelabra",
			"Skyware Candelabra",
			"Spooky Candelabra",
			"Brain Mask",
			"Flesh Mask",
			"Twin Mask",
			"Skeletron Prime Mask",
			"Bee Mask",
			"Plantera Mask",
			"Golem Mask",
			"Eater Mask",
			"Eye Mask",
			"Destroyer Mask",
			"Blacksmith Rack",
			"Carpentry Rack",
			"Helmet Rack",
			"Spear Rack",
			"Sword Rack",
			"Stone Slab",
			"Sandstone Slab",
			"Frog",
			"Mallard Duck",
			"Duck",
			"Honey Bathtub",
			"Steampunk Bathtub",
			"Living Wood Bathtub",
			"Shadewood Bathtub",
			"Bone Bathtub",
			"Honey Lamp",
			"Steampunk Lamp",
			"Living Wood Lamp",
			"Shadewood Lamp",
			"Golden Lamp",
			"Bone Lamp",
			"Living Wood Bookcase",
			"Shadewood Bookcase",
			"Golden Bookcase",
			"Bone Bookcase",
			"Living Wood Bed",
			"Bone Bed",
			"Living Wood Chandelier",
			"Shadewood Chandelier",
			"Golden Chandelier",
			"Bone Chandelier",
			"Living Wood Lantern",
			"Shadewood Lantern",
			"Golden Lantern",
			"Bone Lantern",
			"Living Wood Candelabra",
			"Shadewood Candelabra",
			"Golden Candelabra",
			"Bone Candelabra",
			"Living Wood Candle",
			"Shadewood Candle",
			"Golden Candle",
			"Black Scropion",
			"Scropion",
			"Bubble Wallpaper",
			"Copper Pipe Wallpaper",
			"Ducky Wallpaper",
			"Frost Core",
			"Bunny Cage",
			"Squirrel Cage",
			"Mallard Duck Cage",
			"Duck Cage",
			"Bird Cage",
			"Blue Jay Cage",
			"Cardinal Cage",
			"Waterfall Wall",
			"Lavafall Wall",
			"Crimson Seeds",
			"Heavy Work Bench",
			"Copper Plating",
			"Snail Cage",
			"Glowing Snail Cage",
			"Shroomite Digging Claw",
			"Ammo Box",
			"Monarch Butterfly Jar",
			"Purple Emperor Butterfly Jar",
			"Red Admiral Butterfly Jar",
			"Ulysses Butterfly Jar",
			"Sulphur Butterfly Jar",
			"Tree Nymph Butterfly Jar",
			"Zebra Swallowtail Butterfly Jar",
			"Julia Butterfly Jar",
			"Scorpion Cage",
			"Black Scorpion Cage",
			"Venom Staff",
			"Spectre Mask",
			"Frog Cage",
			"Mouse Cage",
			"Bone Welder",
			"Flesh Cloning Vaat",
			"Glass Kiln",
			"Lihzahrd Furnace",
			"Living Loom",
			"Sky Mill",
			"Ice Machine",
			"Beetle Helmet",
			"Beetle Scale Mail",
			"Beetle Shell",
			"Beetle Leggings",
			"Steampunk Boiler",
			"Honey Dispenser",
			"Penguin",
			"Penguin Cage",
			"Worm Cage",
			"Terrarium",
			"Super Mana Potion",
			"Ebonwood Fence",
			"Rich Mahogany Fence",
			"Pearlwood Fence",
			"Shadewood Fence",
			"Brick Layer",
			"Extendo Grip",
			"Paint Sprayer",
			"Portable Cement Mixer",
			"Beetle Husk",
			"Celestial Magnet",
			"Celestial Emblem",
			"Celestial Cuffs",
			"Peddler's Hat",
			"Pulse Bow",
			"Dynasty Chandelier",
			"Dynasty Lamp",
			"Dynasty Lantern",
			"Dynasty Candelabra",
			"Dynasty Chair",
			"Dynasty Work Bench",
			"Dynasty Chest",
			"Dynasty Bed",
			"Dynasty Bathtub",
			"Dynasty Bookcase",
			"Dynasty Cup",
			"Dynasty Bowl",
			"Dynasty Candle",
			"Dynasty Clock",
			"Golden Clock",
			"Glass Clock",
			"Honey Clock",
			"Steampunk Clock",
			"Fancy Dishes",
			"Glass Bowl",
			"Wine Glass",
			"Living Wood Piano",
			"Flesh Piano",
			"Frozen Piano",
			"Frozen Table",
			"Honey Chest",
			"Steampunk Chest",
			"Honey Work Bench",
			"Frozen Work Bench",
			"Steampunk Work Bench",
			"Glass Piano",
			"Honey Piano",
			"Steampunk Piano",
			"Honey Cup",
			"Steampunk Cup",
			"Dynasty Table",
			"Dynasty Wood",
			"Red Dynasty Shingles",
			"Blue Dynasty Shingles",
			"White Dynasty Wall",
			"Blue Dynasty Wall",
			"Dynasty Door",
			"Sake",
			"Pad Thai",
			"Pho",
			"Revolver",
			"Gatligator",
			"Arcane Rune Wall",
			"Water Gun",
			"Katana",
			"Ultrabright Torch",
			"Magic Hat",
			"Diamond Ring",
			"Gi",
			"Kimono",
			"Gypsy Robe",
			"Beetle Wings",
			"Tiger Skin",
			"Leopard Skin",
			"Zebra Skin",
			"Crimson Cloak",
			"Mysterious Cape",
			"Red Cape",
			"Winter Cape",
			"Frozen Chair",
			"Wood Fishing Pole",
			"Bass",
			"Reinforced Fishing Pole",
			"Fiberglass Fishing Pole",
			"Fisher of Souls",
			"Golden Fishing Rod",
			"Mechanics Rod",
			"Sitting Ducks Fishing Rod",
			"Trout",
			"Salmon",
			"Atlantic Cod",
			"Tuna",
			"Red Snapper",
			"Neon Tetra",
			"Armored Cavefish",
			"Damselfish",
			"Crimson Tigerfish",
			"Frost Minnow",
			"Princess Fish",
			"Golden Carp",
			"Specular Fish",
			"Prismite",
			"Variegated Lardfish",
			"Flarefin Koi",
			"Double Cod",
			"Honeyfin",
			"Obsidifish",
			"Shrimp",
			"Chaos Fish",
			"Ebonkoi",
			"Hemopiranha",
			"Rockfish",
			"Stinkfish",
			"Mining Potion",
			"Heartreach Potion",
			"Calming Potion",
			"Builder Potion",
			"Titan Potion",
			"Flipper Potion",
			"Summoning Potion",
			"Trapsight Potion",
			"Purple Clubberfish",
			"Obsidian Swordfish",
			"Swordfish",
			"Iron Fence",
			"Wooden Crate",
			"Iron Crate",
			"Golden Crate",
			"Old Shoe",
			"Fishing Seaweed",
			"Tin Can",
			"Minecart Track",
			"Reaver Shark",
			"Sawtooth Shark",
			"Minecart",
			"Ammo Reservation Potion",
			"Lifeforce Potion",
			"Endurance Potion",
			"Rage Potion",
			"Inferno Potion",
			"Wrath Potion",
			"Recall Potion",
			"Teleportation Potion",
			"Love Potion",
			"Stink Potion",
			"Fishing Potion",
			"Sonar Potion",
			"Crate Potion",
			"Shiverthorn Seeds",
			"Shiverthorn",
			"Warmth Potion",
			"Fish Hook",
			"Bee Headgear",
			"Bee Breastplate",
			"Bee Greaves",
			"Hornet Staff",
			"Imp Staff",
			"Queen Spider Staff",
			"Angler Hat",
			"Angler Vest",
			"Angler Pants",
			"Spider Mask",
			"Spider Breastplate",
			"Spider Greaves",
			"High Test Fishing Line",
			"Angler Earring",
			"Tackle Box",
			"Blue Dungeon Piano",
			"Green Dungeon Piano",
			"Pink Dungeon Piano",
			"Golden Piano",
			"Obsidian Piano",
			"Bone Piano",
			"Cactus Piano",
			"Spooky Piano",
			"Skyware Piano",
			"Lihzahrd Piano",
			"Blue Dungeon Dresser",
			"Green Dungeon Dresser",
			"Pink Dungeon Dresser",
			"Golden Dresser",
			"Obsidian Dresser",
			"Bone Dresser",
			"Cactus Dresser",
			"Spooky Dresser",
			"Skyware Dresser",
			"Honey Dresser",
			"Lihzahrd Dresser",
			"Sofa",
			"Ebonwood Sofa",
			"Rich Mahogany Sofa",
			"Pearlwood Sofa",
			"Shadewood Sofa",
			"Blue Dungeon Sofa",
			"Green Dungeon Sofa",
			"Pink Dungeon Sofa",
			"Golden Sofa",
			"Obsidian Sofa",
			"Bone Sofa",
			"Cactus Sofa",
			"Spooky Sofa",
			"Skyware Sofa",
			"Honey Sofa",
			"Steampunk Sofa",
			"Mushroom Sofa",
			"Glass Sofa",
			"Pumpkin Sofa",
			"Lihzahrd Sofa",
			"Seashell Hairpin",
			"Mermaid Adornment",
			"Mermaid Tail",
			"Zephyr Fish",
			"Fleshcatcher",
			"Hotline Fishing Hook",
			"Frog Leg",
			"Anchor",
			"Cooked Fish",
			"Cooked Shrimp",
			"Sashimi",
			"Fuzzy Carrot",
			"Scaly Truffle",
			"Slimy Saddle",
			"Bee Wax",
			"Copper Plating Wall",
			"Stone Slab Wall",
			"Sail",
			"Coralstone Block",
			"Blue Jellyfish",
			"Green Jellyfish",
			"Pink Jellyfish",
			"Blue Jellyfish Jar",
			"Green Jellyfish Jar",
			"Pink Jellyfish Jar",
			"Life Preserver",
			"Ships Wheel",
			"Compass Rose",
			"Wall Anchor",
			"Goldfish Trophy",
			"Bunnyfish Trophy",
			"Swordfish Trophy",
			"Sharkteeth Trophy",
			"Batfish",
			"Bublebee Tuna",
			"Catfish",
			"Cloudfish",
			"Cursedfish",
			"Dirtfish",
			"Dynamite Fish",
			"Eater of Plankton",
			"Fallen Starfish",
			"The Fish of Cthulu",
			"Fishotron",
			"Harpyfish",
			"Hungerfish",
			"Ichorfish",
			"Jewelfish",
			"Mirage Fish",
			"Mutant Flinxfin",
			"Pengfish",
			"Pixiefish",
			"Spiderfish",
			"Tundra Trout",
			"Unicorn Fish",
			"Guide Voodoo Fish",
			"Whyverntail",
			"Zombie Fish",
			"Amanitia Fungifin",
			"Angelfish",
			"Bloody Manowar",
			"Bonefish",
			"Bunnyfish",
			"Capn Tunabeard",
			"Clownfish",
			"Demonic Hellfish",
			"Derpfish",
			"Fishron",
			"Infected Scabbardfish",
			"Mudfish",
			"Slimefish",
			"Tropical Barracuda",
			"King Slime Trophy",
			"Ship In ABottle",
			"Hardy Saddle",
			"Pressure Track",
			"King Slime Mask",
			"Fin Wings",
			"Treasure Map",
			"Seaweed Planter",
			"Pillagin Me Pixels",
			"Fish Costume Mask",
			"Fish Costume Shirt",
			"Fish Costume Finskirt",
			"Ginger Beard",
			"Honeyed Goggles",
			"Boreal Wood",
			"Palm Wood",
			"Boreal Wood Wall",
			"Palm Wood Wall",
			"Boreal Wood Fence",
			"Palm Wood Fence",
			"Boreal Wood Helmet",
			"Boreal Wood Breastplate",
			"Boreal Wood Greaves",
			"Palm Wood Helmet",
			"Palm Wood Breastplate",
			"Palm Wood Greaves",
			"Palm Wood Bow",
			"Palm Wood Hammer",
			"Palm Wood Sword",
			"Palm Wood Platform",
			"Palm Wood Bathtub",
			"Palm Wood Bed",
			"Palm Wood Bench",
			"Palm Wood Candelabra",
			"Palm Wood Candle",
			"Palm Wood Chair",
			"Palm Wood Chandelier",
			"Palm Wood Chest",
			"Palm Wood Sofa",
			"Palm Wood Door",
			"Palm Wood Dresser",
			"Palm Wood Lantern",
			"Palm Wood Piano",
			"Palm Wood Table",
			"Palm Wood Lamp",
			"Palm Wood Work Bench",
			"Optic Staff",
			"Palm Wood Bookcase",
			"Mushroom Bathtub",
			"Mushroom Bed",
			"Mushroom Bench",
			"Mushroom Bookcase",
			"Mushroom Candelabra",
			"Mushroom Candle",
			"Mushroom Chandelier",
			"Mushroom Chest",
			"Mushroom Dresser",
			"Mushroom Lantern",
			"Mushroom Lamp",
			"Mushroom Piano",
			"Mushroom Platform",
			"Mushroom Table",
			"Spider Staff",
			"Boreal Wood Bathtub",
			"Boreal Wood Bed",
			"Boreal Wood Bookcase",
			"Boreal Wood Candelabra",
			"Boreal Wood Candle",
			"Boreal Wood Chair",
			"Boreal Wood Chandelier",
			"Boreal Wood Chest",
			"Boreal Wood Clock",
			"Boreal Wood Door",
			"Boreal Wood Dresser",
			"Boreal Wood Lamp",
			"Boreal Wood Lantern",
			"Boreal Wood Piano",
			"Boreal Wood Platform",
			"Slime Bathtub",
			"Slime Bed",
			"Slime Bookcase",
			"Slime Candelabra",
			"Slime Candle",
			"Slime Chair",
			"Slime Chandelier",
			"Slime Chest",
			"Slime Clock",
			"Slime Door",
			"Slime Dresser",
			"Slime Lamp",
			"Slime Lantern",
			"Slime Piano",
			"Slime Platform",
			"Slime Sofa",
			"Slime Table",
			"Pirate Staff",
			"Slime Hook",
			"Sticky Grenade",
			"Tartar Sauce",
			"Duke Fishron Mask",
			"Duke Fishron Trophy",
			"Molotov Cocktail",
			"Bone Clock",
			"Cactus Clock",
			"Ebonwood Clock",
			"Frozen Clock",
			"Lihzahrd Clock",
			"Living Wood Clock",
			"Rich Mahogany Clock",
			"Flesh Clock",
			"Mushroom Clock",
			"Obsidian Clock",
			"Palm Wood Clock",
			"Pearlwood Clock",
			"Pumpkin Clock",
			"Shadewood Clock",
			"Spooky Clock",
			"Sunplate Clock",
			"Spider Fang",
			"Falcon Blade",
			"Fishron Wings",
			"Slime Gun",
			"Flairon",
			"Green Dungeon Chest",
			"Pink Dungeon Chest",
			"Blue Dungeon Chest",
			"Bone Chest",
			"Cactus Chest",
			"Flesh Chest",
			"Obsidian Chest",
			"Pumpkin Chest",
			"Spooky Chest",
			"Tempest Staff",
			"Razorblade Typhoon",
			"Bubble Gun",
			"Tsunami",
			"Seashell",
			"Starfish",
			"Steampunk Platform",
			"Skyware Platform",
			"Living Wood Platform",
			"Honey Platform",
			"Skyware Workbench",
			"Glass Work Bench",
			"Living Wood Work Bench",
			"Flesh Sofa",
			"Frozen Sofa",
			"Living Wood Sofa",
			"Pumpkin Dresser",
			"Steampunk Dresser",
			"Glass Dresser",
			"Flesh Dresser",
			"Pumpkin Lantern",
			"Obsidian Lantern",
			"Pumpkin Lamp",
			"Obsidian Lamp",
			"Blue Dungeon Lamp",
			"Green Dungeon Lamp",
			"Pink Dungeon Lamp",
			"Honey Candle",
			"Steampunk Candle",
			"Spooky Candle",
			"Obsidian Candle",
			"Blue Dungeon Chandelier",
			"Green Dungeon Chandelier",
			"Pink Dungeon Chandelier",
			"Steampunk Chandelier",
			"Pumpkin Chandelier",
			"Obsidian Chandelier",
			"Blue Dungeon Bathtub",
			"Green Dungeon Bathtub",
			"Pink Dungeon Bathtub",
			"Pumpkin Bathtub",
			"Obsidian Bathtub",
			"Golden Bathtub",
			"Blue Dungeon Candelabra",
			"Green Dungeon Candelabra",
			"Pink Dungeon Candelabra",
			"Obsidian Candelabra",
			"Pumpkin Candelabra",
			"Pumpkin Bed",
			"Pumpkin Bookcase",
			"Pumpkin Piano",
			"Shark Statue",
			"Truffle Worm",
			"Apprentice Bait",
			"Journeyman Bait",
			"Master Bait",
			"Amber Gemspark Wall",
			"Amber Gemspark Wall Off",
			"Amethyst Gemspark Wall",
			"Amethyst Gemspark Wall Off",
			"Diamond Gemspark Wall",
			"Diamond Gemspark Wall Off",
			"Emerald Gemspark Wall",
			"Emerald Gemspark Wall Off",
			"Ruby Gemspark Wall",
			"Ruby Gemspark Wall Off",
			"Sapphire Gemspark Wall",
			"Sapphire Gemspark Wall Off",
			"Topaz Gemspark Wall",
			"Topaz Gemspark Wall Off",
			"Tin Plating Wall",
			"Tin Plating",
			"Waterfall Block",
			"Lavafall Block",
			"Confetti Block",
			"Confetti Wall",
			"Confetti Block Black",
			"Confetti Wall Black",
			"Weapon Rack",
			"Fireworks Box",
			"Living Fire Block",
			"Alphabet Statue0",
			"Alphabet Statue1",
			"Alphabet Statue2",
			"Alphabet Statue3",
			"Alphabet Statue4",
			"Alphabet Statue5",
			"Alphabet Statue6",
			"Alphabet Statue7",
			"Alphabet Statue8",
			"Alphabet Statue9",
			"Alphabet Statue A",
			"Alphabet Statue B",
			"Alphabet Statue C",
			"Alphabet Statue D",
			"Alphabet Statue E",
			"Alphabet Statue F",
			"Alphabet Statue G",
			"Alphabet Statue H",
			"Alphabet Statue I",
			"Alphabet Statue J",
			"Alphabet Statue K",
			"Alphabet Statue L",
			"Alphabet Statue M",
			"Alphabet Statue N",
			"Alphabet Statue O",
			"Alphabet Statue P",
			"Alphabet Statue Q",
			"Alphabet Statue R",
			"Alphabet Statue S",
			"Alphabet Statue T",
			"Alphabet Statue U",
			"Alphabet Statue V",
			"Alphabet Statue W",
			"Alphabet Statue X",
			"Alphabet Statue Y",
			"Alphabet Statue Z",
			"Firework Fountain",
			"Booster Track",
			"Grasshopper",
			"Grasshopper Cage",
			"Music Box (Underground Crimson)",
			"Cactus Table",
			"Cactus Platform",
			"Boreal Wood Sword",
			"Boreal Wood Hammer",
			"Boreal Wood Bow",
			"Glass Chest",
			"Celestial Sigil",
			"Logic Gate Lamp (Off)",
			"Logic Gate (AND)",
			"Logic Gate (OR)",
			"Logic Gate (NAND)",
			"Logic Gate (NOR)",
			"Logic Gate (XOR)",
			"Logic Gate (XNOR)",
			"Conveyor Belt (Clockwise)",
			"Conveyor Belt (Counter Clockwise)",
			"The Grand Design",
			"Yellow Wrench",
			"Logic Sensor (Day)",
			"Logic Sensor (Night)",
			"Logic Sensor (Player Above)",
			"Junction Box",
			"Announcement Box",
			"Logic Gate Lamp (On)",
			"Mechanical Lens",
			"Actuation Rod",
			"Red Team Block",
			"Red Team Platform",
			"Static Hook",
			"Presserator",
			"Multicolor Wrench",
			"Pink Weighted Pressure Plate",
			"Engineering Helmet",
			"Companion Cube",
			"Wire Bulb",
			"Orange Weighted Pressure Plate",
			"Purple Weighted Pressure Plate",
			"Cyan Weighted Pressure Plate",
			"Green Team Block",
			"Blue Team Block",
			"Yellow Team Block",
			"Pink Team Block",
			"White Team Block",
			"Green Team Platform",
			"Blue Team Platform",
			"Yellow Team Platform",
			"Pink Team Platform",
			"White Team Platform",
			"Large Amber",
			"Ruby Gem Lock",
			"Sapphire Gem Lock",
			"Emerald Gem Lock",
			"Topaz Gem Lock",
			"Amethyst Gem Lock",
			"Diamond Gem Lock",
			"Amber Gem Lock",
			"Squirrel Statue",
			"Butterfly Statue",
			"Worm Statue",
			"Firefly Statue",
			"Scorpion Statue",
			"Snail Statue",
			"Grasshopper Statue",
			"Mouse Statue",
			"Duck Statue",
			"Penguin Statue",
			"Frog Statue",
			"Buggy Statue",
			"Logic Gate Lamp (Faulty)",
			"Portal Gun Station",
			"Trapped Chest",
			"Trapped Gold Chest",
			"Trapped Shadow Chest",
			"Trapped Ebonwood Chest",
			"Trapped Rich Mahogany Chest",
			"Trapped Pearlwood Chest",
			"Trapped Ivy Chest",
			"Trapped Ice Chest",
			"Trapped Living Wood Chest",
			"Trapped Skyware Chest",
			"Trapped Shadewood Chest",
			"Trapped Web Covered Chest",
			"Trapped Lihzahrd Chest",
			"Trapped Water Chest",
			"Trapped Jungle Chest",
			"Trapped Corruption Chest",
			"Trapped Crimson Chest",
			"Trapped Hallowed Chest",
			"Trapped Frozen Chest",
			"Trapped Dynasty Chest",
			"Trapped Honey Chest",
			"Trapped Steampunk Chest",
			"Trapped Palm Wood Chest",
			"Trapped Mushroom Chest",
			"Trapped Boreal Wood Chest",
			"Trapped Slime Chest",
			"Trapped Green Dungeon Chest",
			"Trapped Pink Dungeon Chest",
			"Trapped Blue Dungeon Chest",
			"Trapped Bone Chest",
			"Trapped Cactus Chest",
			"Trapped Flesh Chest",
			"Trapped Obsidian Chest",
			"Trapped Pumpkin Chest",
			"Trapped Spooky Chest",
			"Trapped Glass Chest",
			"Trapped Martian Chest",
			"Trapped Meteorite Chest",
			"Trapped Granite Chest",
			"Trapped Marble Chest",
			"Trapped Golden Chest",
			"Trapped Crystal Chest",
			"Teal Pressure Pad",
			"Wall Creeper Statue",
			"Unicorn Statue",
			"Drippler Statue",
			"Wraith Statue",
			"Bone Skeleton Statue",
			"Undead Viking Statue",
			"Medusa Statue",
			"Harpy Statue",
			"Pigron Statue",
			"Hoplite Statue",
			"Granite Golem Statue",
			"Armed Zombie Statue",
			"Blood Zombie Statue",
			"Angler Tackle Bag",
			"Geyser",
			"Ultra Bright Campfire",
			"Bone Campfire",
			"Pixel Box",
			"Liquid Sensor (Water)",
			"Liquid Sensor (Lava)",
			"Liquid Sensor (Honey)",
			"Liquid Sensor (Any)",
			"Bundled Party Balloons",
			"Balloon Animal",
			"Party Hat",
			"Silly Sunflower Petals",
			"Silly Sunflower Tops",
			"Silly Sunflower Bottoms",
			"Silly Pink Balloon",
			"Silly Purple Balloon",
			"Silly Green Balloon",
			"Blue Streamer",
			"Green Streamer",
			"Pink Streamer",
			"Silly Balloon Machine",
			"Silly Tied Balloon (Pink)",
			"Silly Tied Balloon (Purple)",
			"Silly Tied Balloon (Green)",
			"Pigronata",
			"Party Center",
			"Silly Tied Bundle of Balloons",
			"Party Present",
			"Slice of Cake",
			"Cog Wall",
			"Sandfall Wall",
			"Snowfall Wall",
			"Sandfall Block",
			"Snowfall Block",
			"Snow Cloud",
			"Pedguin's Hood",
			"Pedguin's Jacket",
			"Pedguin's Trousers",
			"Silly Pink Balloon Wall",
			"Silly Purple Balloon Wall",
			"Silly Green Balloon Wall",
			"0x33's Aviators",
			"Blue Phasesaber",
			"Red Phasesaber",
			"Green Phasesaber",
			"Purple Phasesaber",
			"White Phasesaber",
			"Yellow Phasesaber",
			"Djinn's Curse",
			"Ancient Horn",
			"Mandible Blade",
			"Ancient Headdress",
			"Ancient Garments",
			"Ancient Slacks",
			"Forbidden Mask",
			"Forbidden Robes",
			"Forbidden Treads",
			"Spirit Flame",
			"Sand Elemental Banner",
			"Pocket Mirror",
			"Magic Sand Dropper",
			"Forbidden Fragment",
			"Lamia Tail",
			"Lamia Wraps",
			"Lamia Mask",
			"Sky Fracture",
			"Onyx Blaster",
			"Sand Shark Banner",
			"Bone Biter Banner",
			"Flesh Reaver Banner",
			"Crystal Thresher Banner",
			"Angry Tumbler Banner",
			"Ancient Cloth",
			"Desert Spirit Lamp",
			"Music Box (Sandstorm)",
			"Apprentice's Hat",
			"Apprentice's Robe",
			"Apprentice's Trousers",
			"Squire's Great Helm",
			"Squire's Plating",
			"Squire's Greaves",
			"Huntress's Wig",
			"Huntress's Jerkin",
			"Huntress's Pants",
			"Monk's Bushy Brow Bald Cap",
			"Monk's Shirt",
			"Monk's Pants",
			"Apprentice's Scarf",
			"Squire's Shield",
			"Huntress's Buckler",
			"Monk's Belt",
			"Defender's Forge",
			"War Table",
			"War Table Banner",
			"Eternia Crystal Stand",
			"Defender Medal",
			"Flameburst Rod",
			"Flameburst Cane",
			"Flameburst Staff",
			"Ale Tosser",
			"Etherian Mana",
			"Brand of the Inferno",
			"Ballista Rod",
			"Ballista Cane",
			"Ballista Staff",
			"Flying Dragon",
			"Eternia Crystal",
			"Lightning Aura Rod",
			"Lightning Aura Cane",
			"Lightning Aura Staff",
			"Explosive Trap Rod",
			"Explosive Trap Cane",
			"Explosive Trap Staff",
			"Sleepy Octopod",
			"Ghastly Glaive",
			"Etherian Goblin Bomber Banner",
			"Etherian Goblin Banner",
			"Old One's Skeleton Banner",
			"Drakin Banner",
			"Kobold Glider Banner",
			"Kobold Banner",
			"Wither Beast Banner",
			"Etherian Wyvern Banner",
			"Etherian Javelin Thrower Banner",
			"Etherian Lightning Bug Banner",
			"Tome of Infinite Wisdom",
			"Phantom Phoenix",
			"Gato Egg",
			"Creeper Egg",
			"Dragon Egg",
			"Sky Dragon's Fury",
			"Aerial Bane",
			"Treasure Bag (Betsy)",
			"Treasure Bag (Dark Mage)",
			"Treasure Bag (Ogre)",
			"Betsy Mask",
			"Dark Mage Mask",
			"Ogre Mask",
			"Betsy Trophy",
			"Dark Mage Trophy",
			"Ogre Trophy",
			"Music Box (Old One's Army)",
			"Betsy's Wrath",
			"Valhalla Knight's Helm",
			"Valhalla Knight's Breastplate",
			"Valhalla Knight's Greaves",
			"Dark Artist's Hat",
			"Dark Artist's Robes",
			"Dark Artist's Leggings",
			"Red Riding Hood",
			"Red Riding Dress",
			"Red Riding Leggings",
			"Shinobi Infiltrator's Helmet",
			"Shinobi Infiltrator's Torso",
			"Shinobi Infiltrator's Pants",
			"Betsy's Wings",
			"Platinum Bow",
			"Platinum Hammer",
			"Platinum Axe",
			"Platinum Shortsword",
			"Platinum Broadsword",
			"Platinum Pickaxe",
			"Tungsten Bow",
			"Tungsten Hammer",
			"Tungsten Axe",
			"Tungsten Shortsword",
			"Tungsten Broadsword",
			"Tungsten Pickaxe",
			"Lead Bow",
			"Lead Hammer",
			"Lead Axe",
			"Lead Shortsword",
			"Lead Broadsword",
			"Lead Pickaxe",
			"Tin Bow",
			"Tin Hammer",
			"Tin Axe",
			"Tin Shortsword",
			"Tin Broadsword",
			"Tin Pickaxe",
			"Yellow Phasesaber",
			"White Phasesaber",
			"Purple Phasesaber",
			"Green Phasesaber",
			"Red Phasesaber",
			"Blue Phasesaber",
			"Copper Bow",
			"Copper Hammer",
			"Copper Axe",
			"Copper Shortsword",
			"Copper Broadsword",
			"Copper Pickaxe",
			"Silver Bow",
			"Silver Hammer",
			"Silver Axe",
			"Silver Shortsword",
			"Silver Broadsword",
			"Silver Pickaxe",
			"Gold Bow",
			"Gold Hammer",
			"Gold Axe",
			"Gold Shortsword",
			"Gold Broadsword",
			"Gold Pickaxe"
		};
	}
}